class ArticleAnalyzer:


    def __init__(self):

        self.tech_categories = {

            "LFP": [
                "lfp",
                "lithium iron phosphate",
                "磷酸铁锂"
            ],

            "LMR": [
                "lmr",
                "lithium rich manganese",
                "富锂锰基"
            ],

            "Sodium-ion": [
                "sodium",
                "sodium-ion",
                "钠离子"
            ]
        }



    def classify_technology(
        self,
        article
    ):


        text = (

            article.get(
                "title",
                ""
            )
            +
            " "
            +
            article.get(
                "keyword",
                ""
            )

        ).lower()



        result = []


        for category, keywords in self.tech_categories.items():


            for keyword in keywords:


                if keyword.lower() in text:

                    result.append(
                        category
                    )

                    break



        return result



    def analyze(
        self,
        article
    ):


        technology = self.classify_technology(
            article
        )


        result = {


            "original_title":
            article.get(
                "title",
                ""
            ),


            "source":
            article.get(
                "source",
                ""
            ),


            "link":
            article.get(
                "link",
                ""
            ),


            "technology":
            technology,


            "summary":
            "Technical summary will be generated by AI module.",


            "research_note":
            "Requires technical evaluation."

        }


        return result
